// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:rick_and_morty/characters/entity/character.dart';
import 'package:rick_and_morty/characters/entity/character_location.dart';
import 'package:rick_and_morty/characters/entity/character_status.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CharacterAdapter());
    registerAdapter(CharacterLocationAdapter());
    registerAdapter(CharacterStatusAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CharacterAdapter());
    registerAdapter(CharacterLocationAdapter());
    registerAdapter(CharacterStatusAdapter());
  }
}
